"""Generated human-facing checkpoint documents.

Builds a root-facing reading layer from the canonical per-phase SUMMARY and
VERIFICATION artifacts plus archived milestone audit and digest artifacts. The
generated outputs are deterministic:

- one ``phase-checkpoints/<phase-dir>.md`` file per phase that has summaries
- one ``milestone-checkpoints/<version>.md`` file per archived milestone
- one root ``CHECKPOINTS.md`` index covering the whole project

The canonical source of truth remains ``.gpd/phases/.../*-SUMMARY.md`` and
``*-VERIFICATION.md`` for phases plus ``.gpd/milestones/...`` audit and digest
artifacts for milestones. This module only derives readable checkpoint notes
from those artifacts.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from functools import cmp_to_key
from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field

from gpd.core.commands import SummaryExtractResult, cmd_summary_extract
from gpd.core.constants import (
    STANDALONE_SUMMARY,
    STANDALONE_VERIFICATION,
    ProjectLayout,
)
from gpd.core.frontmatter import FrontmatterParseError, extract_frontmatter
from gpd.core.observability import instrument_gpd_function
from gpd.core.utils import atomic_write, compare_phase_numbers, safe_read_file

__all__ = [
    "SyncPhaseCheckpointsResult",
    "sync_phase_checkpoints",
]

_GENERATED_HEADER = "<!-- Generated by gpd sync-phase-checkpoints. Do not edit by hand. -->"


class SyncPhaseCheckpointsResult(BaseModel):
    """Report from syncing generated checkpoint artifacts."""

    model_config = ConfigDict(frozen=True)

    generated: bool
    phase_count: int
    milestone_count: int
    checkpoint_dir: str
    milestone_checkpoint_dir: str
    root_index: str
    updated_files: list[str] = Field(default_factory=list)
    removed_files: list[str] = Field(default_factory=list)


@dataclass(frozen=True)
class _PhaseSummaryDoc:
    phase_number: str
    phase_title: str
    summary_path: Path
    plan: str
    completed: str
    one_liner: str
    body: str
    provides: list[str]
    summary_extract: SummaryExtractResult


@dataclass(frozen=True)
class _MilestoneRow:
    version: str
    name: str
    status: str
    started: str
    completed: str
    notes: str


@dataclass(frozen=True)
class _MilestoneAuditDoc:
    path: Path
    version: str
    audited: str
    status: str
    milestone_question: str
    verdict_body: str
    open_questions: list[str]
    body: str


@dataclass(frozen=True)
class _MilestoneDigestDoc:
    path: Path
    narrative_arc: str
    key_results: list[str]
    body: str


@dataclass(frozen=True)
class _MilestoneDoc:
    version: str
    name: str
    status: str
    completed: str
    notes: str
    audit: _MilestoneAuditDoc
    digest: _MilestoneDigestDoc | None
    roadmap_path: Path | None
    requirements_path: Path | None


def _title_from_phase_dir(phase_dir_name: str) -> tuple[str, str]:
    prefix, _, slug = phase_dir_name.partition("-")
    title = " ".join(part.capitalize() for part in slug.split("-") if part)
    return prefix or phase_dir_name, title or "Untitled Phase"


def _clean_sentence(text: str) -> str:
    value = " ".join(text.strip().split())
    value = value.strip().strip('"').strip("'")
    if not value:
        return ""
    if value[-1] not in ".!?":
        value += "."
    return value


def _clean_clause(text: str) -> str:
    value = " ".join(text.strip().split())
    value = re.sub(r"^Status:\s*`[^`]+`\s*", "", value)
    value = re.sub(r"^Open:\s*", "", value)
    value = value.strip().strip('"').strip("'")
    value = value.rstrip(".!?")
    return value


def _ensure_leading_capital(text: str) -> str:
    value = text.lstrip()
    if not value:
        return ""
    if value[0].isalpha():
        return value[0].upper() + value[1:]
    return value


def _natural_join(items: list[str]) -> str:
    cleaned = [_clean_sentence(item) for item in items if _clean_sentence(item)]
    if not cleaned:
        return ""
    if len(cleaned) == 1:
        return cleaned[0]
    if len(cleaned) == 2:
        return f"{cleaned[0]} {cleaned[1]}"
    return " ".join(cleaned)


def _summarize_phrases(items: list[str], *, limit: int = 3) -> str:
    cleaned = [_clean_clause(item) for item in items if _clean_clause(item)]
    if not cleaned:
        return ""
    trimmed = cleaned[:limit]
    if len(trimmed) == 1:
        return trimmed[0]
    if len(trimmed) == 2:
        return f"{trimmed[0]} and {trimmed[1]}"
    return f"{', '.join(trimmed[:-1])}, and {trimmed[-1]}"


def _prefixed_summary(prefix: str, items: list[str], *, limit: int = 3) -> str:
    cleaned = [" ".join(item.strip().split()) for item in items if item.strip()]
    if not cleaned:
        return ""
    trimmed = cleaned[:limit]
    if len(trimmed) == 1:
        summary = trimmed[0]
    elif len(trimmed) == 2:
        summary = f"{trimmed[0]} and {trimmed[1]}"
    else:
        summary = f"{', '.join(trimmed[:-1])}, and {trimmed[-1]}"
    return _clean_sentence(f"{prefix}{summary}")


def _extract_next_step(body: str) -> str:
    compact = " ".join(body.split())
    patterns = (
        r"(The next clean move is [^.]+\.)",
        r"(The next best step is [^.]+\.)",
        r"(The next move is [^.]+\.)",
        r"(The next clean discussion checkpoint is [^.]+\.)",
    )
    for pattern in patterns:
        match = re.search(pattern, compact)
        if match:
            return match.group(1)
    return ""


def _strip_top_heading(body: str) -> str:
    stripped = body.strip()
    return re.sub(r"^# .+\n+", "", stripped, count=1).strip()


def _summary_sort_key(path: Path) -> tuple[int, str]:
    if path.name == STANDALONE_SUMMARY:
        return (1, path.name)
    return (0, path.name)


def _verification_sort_key(path: Path) -> tuple[int, str]:
    if path.name == STANDALONE_VERIFICATION:
        return (1, path.name)
    return (0, path.name)


def _phase_summary_docs(cwd: Path, phase_dir: Path) -> list[_PhaseSummaryDoc]:
    layout = ProjectLayout(cwd)
    docs: list[_PhaseSummaryDoc] = []

    for summary_path in sorted(
        [path for path in phase_dir.iterdir() if path.is_file() and layout.is_summary_file(path.name)],
        key=_summary_sort_key,
    ):
        content = safe_read_file(summary_path)
        if content is None:
            continue
        try:
            frontmatter, body = extract_frontmatter(content)
        except FrontmatterParseError as exc:
            raise ValueError(f"Failed to parse {summary_path.relative_to(cwd)}: {exc}") from exc

        phase_number, phase_title = _title_from_phase_dir(phase_dir.name)
        summary_relpath = summary_path.relative_to(cwd).as_posix()
        extracted = cmd_summary_extract(cwd, summary_relpath)
        raw_dependency_graph = frontmatter.get("dependency-graph")
        if isinstance(raw_dependency_graph, dict):
            raw_provides = raw_dependency_graph.get("provides")
        else:
            raw_provides = frontmatter.get("provides")
        provides = [str(item).strip() for item in raw_provides or [] if str(item).strip()] if isinstance(
            raw_provides, list
        ) else []
        docs.append(
            _PhaseSummaryDoc(
                phase_number=str(frontmatter.get("phase") or phase_number).strip() or phase_number,
                phase_title=phase_title,
                summary_path=summary_path,
                plan=str(frontmatter.get("plan") or "").strip(),
                completed=str(frontmatter.get("completed") or "").strip(),
                one_liner=(extracted.one_liner or "").strip(),
                body=_strip_top_heading(body),
                provides=provides,
                summary_extract=extracted,
            )
        )

    return docs


def _verification_paths(cwd: Path, phase_dir: Path) -> list[str]:
    layout = ProjectLayout(cwd)
    return [
        path.relative_to(cwd).as_posix()
        for path in sorted(
            [candidate for candidate in phase_dir.iterdir() if candidate.is_file() and layout.is_verification_file(candidate.name)],
            key=_verification_sort_key,
        )
    ]


def _render_story_paragraphs(doc: _PhaseSummaryDoc, plan_count: int) -> list[str]:
    paragraphs: list[str] = []
    intro = f"Phase {doc.phase_number} focused on {doc.phase_title.lower()}."
    if doc.completed:
        intro += f" It closed on {doc.completed}."
    if doc.one_liner:
        intro += f" The headline result was straightforward: {_clean_sentence(doc.one_liner)}"
    if plan_count > 1:
        intro += f" This checkpoint reflects the latest of {plan_count} recorded plan summaries for the phase."
    paragraphs.append(intro)

    decisions = [
        _clean_sentence(
            decision.summary if not decision.rationale else f"{decision.summary}: {decision.rationale}"
        )
        for decision in doc.summary_extract.decisions[:4]
    ]
    if decisions:
        paragraphs.append(f"The main project decisions were concrete. {_natural_join(decisions)}")

    provides = _prefixed_summary(
        "In practical terms, this phase now gives the project ",
        doc.provides or doc.summary_extract.affects or doc.summary_extract.key_files or [],
        limit=4,
    )
    if provides:
        paragraphs.append(provides)

    patterns = _natural_join(doc.summary_extract.patterns[:3])
    if patterns:
        paragraphs.append(f"What this phase clarified was simple. {patterns}")

    next_step = _extract_next_step(doc.body)
    if next_step:
        paragraphs.append(next_step)

    return [paragraph for paragraph in paragraphs if paragraph]


def _render_phase_checkpoint(cwd: Path, phase_dir: Path, docs: list[_PhaseSummaryDoc]) -> str:
    latest = docs[-1]
    checkpoint_dir = ProjectLayout(cwd).phase_checkpoints_dir
    verification_paths = _verification_paths(cwd, phase_dir)

    lines: list[str] = [
        _GENERATED_HEADER,
        "",
        f"# Phase {latest.phase_number} Checkpoint",
        "",
        f"_Title: {latest.phase_title}_",
    ]
    if latest.completed:
        lines.append(f"_Completed: {latest.completed}_")
    lines.append("")

    for paragraph in _render_story_paragraphs(latest, len(docs)):
        lines.append(paragraph)
        lines.append("")

    lines.extend(
        [
            "## Read This Phase",
            "",
        ]
    )

    for doc in docs:
        link = os.path.relpath(doc.summary_path, checkpoint_dir)
        label = f"Plan {doc.plan or '?'} summary"
        if doc is latest:
            label = f"Latest summary ({doc.summary_path.name})"
        lines.append(f"- {label}: [{doc.summary_path.name}]({link})")

    for verification_path in verification_paths:
        verification_file = cwd / verification_path
        link = os.path.relpath(verification_file, checkpoint_dir)
        lines.append(f"- Verification: [{verification_file.name}]({link})")

    key_files = list(dict.fromkeys(latest.summary_extract.key_files))
    for key_file in key_files[:5]:
        lines.append(f"- Primary artifact: `{key_file}`")

    lines.extend(
        [
            "",
            "## Detailed Notes",
            "",
        ]
    )

    if latest.body:
        lines.append(latest.body)
        lines.append("")

    if len(docs) > 1:
        lines.extend(
            [
                "## Earlier Plan Notes",
                "",
            ]
        )
        for doc in docs[:-1]:
            link = os.path.relpath(doc.summary_path, checkpoint_dir)
            lines.append(f"### Plan {doc.plan or '?'}")
            lines.append("")
            if doc.one_liner:
                lines.append(_clean_sentence(doc.one_liner))
                lines.append("")
            lines.append(f"Read the full earlier summary here: [{doc.summary_path.name}]({link})")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _parse_markdown_sections(body: str) -> dict[str, str]:
    sections: dict[str, str] = {}
    matches = list(re.finditer(r"(?m)^## (.+)$", body))
    for index, match in enumerate(matches):
        title = match.group(1).strip()
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(body)
        sections[title] = body[start:end].strip()
    return sections


def _parse_milestones_table(layout: ProjectLayout) -> dict[str, _MilestoneRow]:
    rows: dict[str, _MilestoneRow] = {}
    content = safe_read_file(layout.milestones_md)
    if not content:
        return rows
    for line in content.splitlines():
        if not line.startswith("| `v"):
            continue
        parts = [part.strip() for part in line.strip().strip("|").split("|")]
        if len(parts) < 6:
            continue
        version = parts[0].strip("`")
        rows[version] = _MilestoneRow(
            version=version,
            name=parts[1],
            status=parts[2],
            started=parts[3],
            completed=parts[4],
            notes=parts[5],
        )
    return rows


def _milestone_sort_key(version: str) -> tuple[int, ...]:
    numeric = version.lstrip("vV")
    return tuple(int(part) for part in numeric.split("."))


def _parse_milestone_audit(cwd: Path, path: Path) -> _MilestoneAuditDoc:
    content = safe_read_file(path)
    if content is None:
        raise ValueError(f"Failed to read {path.relative_to(cwd)}")
    try:
        frontmatter, body = extract_frontmatter(content)
    except FrontmatterParseError:
        frontmatter = {}
        body = content

    stripped_body = _strip_top_heading(body)
    sections = _parse_markdown_sections(stripped_body)
    open_questions: list[str] = []
    raw_open = frontmatter.get("open_questions")
    if isinstance(raw_open, list):
        for item in raw_open:
            if isinstance(item, dict):
                values = item.get("items")
                if isinstance(values, list):
                    open_questions.extend(str(value) for value in values)
            elif isinstance(item, str):
                open_questions.append(item)

    version = str(frontmatter.get("milestone") or path.stem.replace("-MILESTONE-AUDIT", "")).strip()
    return _MilestoneAuditDoc(
        path=path,
        version=version,
        audited=str(frontmatter.get("audited") or "").strip(),
        status=str(frontmatter.get("status") or "").strip(),
        milestone_question=sections.get("Milestone Question", ""),
        verdict_body=sections.get("Verdict", ""),
        open_questions=open_questions,
        body=stripped_body,
    )


def _parse_milestone_digest(cwd: Path, path: Path) -> _MilestoneDigestDoc:
    content = safe_read_file(path)
    if content is None:
        raise ValueError(f"Failed to read {path.relative_to(cwd)}")
    stripped_body = _strip_top_heading(content)
    sections = _parse_markdown_sections(stripped_body)
    key_results: list[str] = []
    key_result_section = sections.get("Key Results", "")
    for line in key_result_section.splitlines():
        if not line.startswith("|"):
            continue
        parts = [part.strip() for part in line.strip().strip("|").split("|")]
        if len(parts) >= 2 and parts[0] not in {"Phase", "-----"}:
            key_results.append(parts[1])
    return _MilestoneDigestDoc(
        path=path,
        narrative_arc=sections.get("Narrative Arc", ""),
        key_results=key_results,
        body=stripped_body,
    )


def _milestone_audit_paths(layout: ProjectLayout) -> list[Path]:
    audit_paths: dict[str, Path] = {}
    if layout.milestones_dir.is_dir():
        for path in layout.milestones_dir.glob("v*-MILESTONE-AUDIT.md"):
            audit_paths[path.stem.replace("-MILESTONE-AUDIT", "")] = path
    if layout.gpd.is_dir():
        for path in layout.gpd.glob("v*-MILESTONE-AUDIT.md"):
            version = path.stem.replace("-MILESTONE-AUDIT", "")
            audit_paths.setdefault(version, path)
    return [audit_paths[version] for version in sorted(audit_paths, key=_milestone_sort_key)]


def _load_milestone_docs(cwd: Path) -> list[_MilestoneDoc]:
    layout = ProjectLayout(cwd)
    milestone_rows = _parse_milestones_table(layout)
    docs: list[_MilestoneDoc] = []

    for audit_path in _milestone_audit_paths(layout):
        audit = _parse_milestone_audit(cwd, audit_path)
        row = milestone_rows.get(
            audit.version,
            _MilestoneRow(version=audit.version, name=audit.version, status="", started="", completed="", notes=""),
        )
        digest_path = layout.milestones_dir / audit.version / "RESEARCH-DIGEST.md"
        roadmap_path = layout.milestones_dir / f"{audit.version}-ROADMAP.md"
        requirements_path = layout.milestones_dir / f"{audit.version}-REQUIREMENTS.md"
        docs.append(
            _MilestoneDoc(
                version=audit.version,
                name=row.name or audit.version,
                status=audit.status or row.status,
                completed=row.completed if row.completed and row.completed != "—" else "",
                notes=row.notes,
                audit=audit,
                digest=_parse_milestone_digest(cwd, digest_path) if digest_path.exists() else None,
                roadmap_path=roadmap_path if roadmap_path.exists() else None,
                requirements_path=requirements_path if requirements_path.exists() else None,
            )
        )

    return docs


def _milestone_headline(doc: _MilestoneDoc) -> str:
    if doc.digest and doc.digest.narrative_arc:
        return _clean_sentence(doc.digest.narrative_arc.split(". ", 1)[0].strip())

    paragraphs = [paragraph.strip() for paragraph in doc.audit.verdict_body.split("\n\n") if paragraph.strip()]
    for paragraph in paragraphs:
        cleaned = _clean_clause(paragraph)
        if cleaned:
            return _clean_sentence(cleaned)

    return _clean_sentence(doc.notes or f"{doc.version} closed with audit status {doc.status}.")


def _render_milestone_story_paragraphs(doc: _MilestoneDoc) -> list[str]:
    paragraphs: list[str] = []
    intro = f"Milestone {doc.version} focused on {doc.name.lower()}."
    if doc.completed:
        intro += f" It closed on {doc.completed}."
    if doc.status:
        intro += f" The audit status was `{doc.status}`."
    headline = _milestone_headline(doc)
    if headline:
        intro += f" The headline result was straightforward: {headline}"
    paragraphs.append(intro)

    key_results = _summarize_phrases(doc.digest.key_results if doc.digest else [], limit=4)
    if key_results:
        paragraphs.append(f"The main milestone decisions were concrete. {_clean_sentence(key_results)}")

    artifact_bits: list[str] = []
    if doc.roadmap_path:
        artifact_bits.append("archived roadmap")
    if doc.requirements_path:
        artifact_bits.append("archived requirements")
    artifact_bits.append("archived audit")
    if doc.digest:
        artifact_bits.append("research digest")
    artifact_summary = _summarize_phrases(artifact_bits, limit=4)
    if artifact_summary:
        paragraphs.append(_clean_sentence(f"In practical terms, this milestone now gives the project {artifact_summary}"))

    open_questions = _summarize_phrases(doc.audit.open_questions, limit=3)
    if open_questions:
        paragraphs.append(
            f"What remains open is still bounded. {_clean_sentence(_ensure_leading_capital(open_questions))}"
        )
    elif doc.notes:
        paragraphs.append(_clean_sentence(doc.notes))

    return [paragraph for paragraph in paragraphs if paragraph]


def _render_milestone_checkpoint(cwd: Path, doc: _MilestoneDoc) -> str:
    checkpoint_dir = ProjectLayout(cwd).milestone_checkpoints_dir
    lines: list[str] = [
        _GENERATED_HEADER,
        "",
        f"# Milestone {doc.version} Checkpoint",
        "",
        f"_Title: {doc.name}_",
    ]
    if doc.completed:
        lines.append(f"_Completed: {doc.completed}_")
    if doc.status:
        lines.append(f"_Audit status: {doc.status}_")
    lines.append("")

    for paragraph in _render_milestone_story_paragraphs(doc):
        lines.append(paragraph)
        lines.append("")

    lines.extend(
        [
            "## Read This Milestone",
            "",
            f"- Audit: [{doc.audit.path.name}]({os.path.relpath(doc.audit.path, checkpoint_dir)})",
        ]
    )
    if doc.digest:
        lines.append(f"- Research digest: [{doc.digest.path.name}]({os.path.relpath(doc.digest.path, checkpoint_dir)})")
    if doc.roadmap_path:
        lines.append(f"- Archived roadmap: [{doc.roadmap_path.name}]({os.path.relpath(doc.roadmap_path, checkpoint_dir)})")
    if doc.requirements_path:
        lines.append(
            f"- Archived requirements: [{doc.requirements_path.name}]({os.path.relpath(doc.requirements_path, checkpoint_dir)})"
        )
    lines.append("")

    if doc.digest:
        lines.extend(["## Research Digest", "", doc.digest.body, ""])

    lines.extend(["## Audit Notes", "", doc.audit.body, ""])
    return "\n".join(lines).rstrip() + "\n"


def _render_milestone_index_entry(layout: ProjectLayout, doc: _MilestoneDoc) -> str:
    line = f"- [Milestone {doc.version}: {doc.name}]({layout.milestone_checkpoint_file(doc.version).relative_to(layout.root).as_posix()})"
    headline = _milestone_headline(doc)
    if headline:
        line += f" — {headline}"
    return line


def _render_root_index(
    cwd: Path,
    phase_groups: list[tuple[Path, list[_PhaseSummaryDoc]]],
    milestone_docs: list[_MilestoneDoc],
) -> str:
    lines = [
        _GENERATED_HEADER,
        "",
        "# Checkpoints",
        "",
        "This is the human-facing checkpoint shelf for the project.",
        "Phase notes are generated from the canonical SUMMARY and VERIFICATION artifacts under `.gpd/phases/`.",
        "Milestone notes are generated from archived audit and digest artifacts under `.gpd/milestones/`.",
        "",
        "Read one checkpoint file when you want the end-of-cycle story in plain English.",
        "Use the linked summary, verification, audit, and digest artifacts when you want the full underlying record.",
        "",
    ]

    layout = ProjectLayout(cwd)

    if milestone_docs:
        lines.extend(["## Milestone Index", ""])
        for doc in milestone_docs:
            lines.append(_render_milestone_index_entry(layout, doc))
        lines.append("")

    lines.extend(["## Phase Index", ""])
    for phase_dir, docs in phase_groups:
        latest = docs[-1]
        link = layout.phase_checkpoint_file(phase_dir.name).relative_to(cwd).as_posix()
        line = f"- [Phase {latest.phase_number}: {latest.phase_title}]({link})"
        if latest.one_liner:
            line += f" — {latest.one_liner}"
        lines.append(line)

    lines.append("")
    return "\n".join(lines)


def _write_if_changed(path: Path, content: str) -> bool:
    existing = safe_read_file(path)
    if existing == content:
        return False
    atomic_write(path, content)
    return True


@instrument_gpd_function("checkpoints.sync_phase_checkpoints")
def sync_phase_checkpoints(cwd: Path) -> SyncPhaseCheckpointsResult:
    """Generate the root-facing checkpoint shelf from phase and milestone artifacts."""
    layout = ProjectLayout(cwd)
    layout.phase_checkpoints_dir.mkdir(parents=True, exist_ok=True)
    layout.milestone_checkpoints_dir.mkdir(parents=True, exist_ok=True)

    phase_groups: list[tuple[Path, list[_PhaseSummaryDoc]]] = []
    milestone_docs = _load_milestone_docs(cwd)
    updated_files: list[str] = []
    removed_files: list[str] = []

    if layout.phases_dir.is_dir():
        for phase_dir in sorted(
            [path for path in layout.phases_dir.iterdir() if path.is_dir()],
            key=cmp_to_key(lambda a, b: compare_phase_numbers(a.name, b.name)),
        ):
            docs = _phase_summary_docs(cwd, phase_dir)
            if not docs:
                continue
            phase_groups.append((phase_dir, docs))
            checkpoint_path = layout.phase_checkpoint_file(phase_dir.name)
            content = _render_phase_checkpoint(cwd, phase_dir, docs)
            if _write_if_changed(checkpoint_path, content):
                updated_files.append(checkpoint_path.relative_to(cwd).as_posix())

    for doc in milestone_docs:
        checkpoint_path = layout.milestone_checkpoint_file(doc.version)
        content = _render_milestone_checkpoint(cwd, doc)
        if _write_if_changed(checkpoint_path, content):
            updated_files.append(checkpoint_path.relative_to(cwd).as_posix())

    expected_checkpoint_paths = {
        layout.phase_checkpoint_file(phase_dir.name).resolve()
        for phase_dir, _docs in phase_groups
    }
    for existing in sorted(
        [path for path in layout.phase_checkpoints_dir.glob("*.md") if not path.name.startswith("._")]
    ):
        if existing.resolve() in expected_checkpoint_paths:
            continue
        existing.unlink()
        removed_files.append(existing.relative_to(cwd).as_posix())

    expected_milestone_paths = {
        layout.milestone_checkpoint_file(doc.version).resolve()
        for doc in milestone_docs
    }
    for existing in sorted(
        [path for path in layout.milestone_checkpoints_dir.glob("*.md") if not path.name.startswith("._")]
    ):
        if existing.resolve() in expected_milestone_paths:
            continue
        existing.unlink()
        removed_files.append(existing.relative_to(cwd).as_posix())

    root_content = _render_root_index(cwd, phase_groups, milestone_docs)
    if _write_if_changed(layout.checkpoints_md, root_content):
        updated_files.append(layout.checkpoints_md.relative_to(cwd).as_posix())

    return SyncPhaseCheckpointsResult(
        generated=True,
        phase_count=len(phase_groups),
        milestone_count=len(milestone_docs),
        checkpoint_dir=layout.phase_checkpoints_dir.relative_to(cwd).as_posix(),
        milestone_checkpoint_dir=layout.milestone_checkpoints_dir.relative_to(cwd).as_posix(),
        root_index=layout.checkpoints_md.relative_to(cwd).as_posix(),
        updated_files=updated_files,
        removed_files=removed_files,
    )
